apiVersion: v1
kind: Secret
metadata:
  name: nexus-docker
  namespace: misc
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "api,nexus,service,sso"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1cy5xdWFzYXJpdW0ubmV0L2RvY2tlci1wdWJsaWMiOnsidXNlcm5hbWUiOiJueC1naXRodWIiLCJwYXNzd29yZCI6IkxoRy05SjMtazlFLWI0ayIsImVtYWlsIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImF1dGgiOiJibmd0WjJsMGFIVmlPa3hvUnkwNVNqTXRhemxGTFdJMGF3PT0ifX19
