apiVersion: v1
kind: Secret
metadata:
  name: nexus-postgres-cluster-role
  namespace: nexus
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: "nexus"
  password: "2852209a8abb86b7d060f97559d31366"
