apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: docs-server-v1
  namespace: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docs-server
      app.kubernetes.io/version: v1
