apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: sso
#  annotations:
#    cnpg.io/reconciliationLoop: "disabled"
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: master
    major: 18
  imagePullPolicy: Always
  instances: 3
  postgresql:
    parameters:
      shared_buffers: "256MB"
  storage:
    storageClass: native-storage
    size: 16Gi
    pvcTemplate:
      selector:
        matchLabels:
          app.kubernetes.io/name: sso-postgres-cluster-volume
  managed:
    roles:
      - name: keycloak
        passwordSecret:
          name: keycloak-postgres-cluster-role
        login: true
        createdb: true
  monitoring:
    tls:
      enabled: true
  resources:
    limits:
      memory: "1024Mi"
      cpu: "100m"
    requests:
      memory: "512Mi"
      cpu: "50m"
