apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-cluster-role
  namespace: sso
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: "keycloak"
  password: "88af782fd5cf1ca5a3093cb956219d09"
