apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: inventory-postgres-cluster
  namespace: api
spec:
  cluster:
    name: postgres-cluster
  name: inventory
  owner: inventory
  template: "template0"
  encoding: "UTF8"
  localeCollate: "C"
  localeCType: "C"
