apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-v1
  namespace: web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/version: v1
