apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongodb-cluster
  namespace: api
  finalizers:
    - percona.com/delete-psmdb-pods-in-order
spec:
  initImage: percona/percona-server-mongodb-operator:1.21.1
  image: percona/percona-server-mongodb:8.0.12-4
  imagePullPolicy: Always
  enableVolumeExpansion: true
  clusterServiceDNSMode: ServiceMesh
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: Disabled
    schedule: "0 2 * * *"
    setFCV: true
  replsets:
    - name: rs0
      size: 3
      affinity:
        antiAffinityTopologyKey: none
      podDisruptionBudget:
        minAvailable: 1
      expose:
        enabled: true
        type: ClusterIP
      resources:
        limits:
          cpu: "600m"
          memory: "1Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: native-storage
          selector:
            matchLabels:
              app.kubernetes.io/name: api-mongodb-cluster-volume
          resources:
            requests:
              storage: 16Gi
  sharding:
    enabled: true
    configsvrReplSet:
      size: 3
      affinity:
        antiAffinityTopologyKey: none
      podDisruptionBudget:
        minAvailable: 1
      expose:
        enabled: true
        type: ClusterIP
      resources:
        limits:
          cpu: "600m"
          memory: "1Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: native-storage
          selector:
            matchLabels:
              app.kubernetes.io/name: api-mongodb-cluster-config-volume
          resources:
            requests:
              storage: 4Gi
    mongos:
      size: 3
      affinity:
        antiAffinityTopologyKey: none
      podDisruptionBudget:
        minAvailable: 1
      resources:
        limits:
          cpu: "600m"
          memory: "1Gi"
        requests:
          cpu: "300m"
          memory: "1Gi"
  roles:
    - role: cart
      db: cart
      privileges:
        - resource:
            db: cart
            collection: ""
          actions:
            - find
            - insert
            - update
            - remove
            - createIndex
            - dropIndex
            - bypassDocumentValidation
    - role: notifications
      db: notifications
      privileges:
        - resource:
            db: notifications
            collection: ""
          actions:
            - find
            - insert
            - update
            - remove
            - createIndex
            - dropIndex
            - bypassDocumentValidation
    - role: orders
      db: orders
      privileges:
        - resource:
            db: orders
            collection: ""
          actions:
            - find
            - insert
            - update
            - remove
            - createIndex
            - dropIndex
            - bypassDocumentValidation
    - role: payments
      db: payments
      privileges:
        - resource:
            db: payments
            collection: ""
          actions:
            - find
            - insert
            - update
            - remove
            - createIndex
            - dropIndex
            - bypassDocumentValidation
    - role: products
      db: products
      privileges:
        - resource:
            db: products
            collection: ""
          actions:
            - find
            - insert
            - update
            - remove
            - createIndex
            - dropIndex
            - bypassDocumentValidation
  users:
    - name: exporter
      db: admin
      passwordSecretRef:
        name: mongodb-cluster-exporter-user
        key: password
      roles:
        - name: clusterMonitor
          db: admin
        - name: read
          db: local
    - name: cart
      db: admin
      passwordSecretRef:
        name: cart-mongodb-cluster-user
        key: password
      roles:
        - name: cart
          db: cart
    - name: notifications
      db: admin
      passwordSecretRef:
        name: notifications-mongodb-cluster-user
        key: password
      roles:
        - name: notifications
          db: notifications
    - name: orders
      db: admin
      passwordSecretRef:
        name: orders-mongodb-cluster-user
        key: password
      roles:
        - name: orders
          db: orders
    - name: payments
      db: admin
      passwordSecretRef:
        name: payments-mongodb-cluster-user
        key: password
      roles:
        - name: payments
          db: payments
    - name: products
      db: admin
      passwordSecretRef:
        name: products-mongodb-cluster-user
        key: password
      roles:
        - name: products
          db: products
