apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: products-v1
  namespace: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: products
      app.kubernetes.io/version: v1
