apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alloy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
    spec:
      automountServiceAccountToken: false
      serviceAccountName: alloy
      containers:
        - name: alloy
          image: grafana/alloy:latest
          imagePullPolicy: Always
          args:
            - "run"
            - "--server.http.listen-addr=0.0.0.0:12345"
            - "--server.http.ui-path-prefix=/alloy"
            - "--storage.path=/var/lib/alloy/data"
            - "/etc/alloy/config.alloy"
          ports:
            - name: http
              containerPort: 12345
          readinessProbe:
            httpGet:
              path: /alloy/-/ready
              port: http
          livenessProbe:
            httpGet:
              path: /alloy/-/healthy
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: alloy-config-volume
              mountPath: /etc/alloy
              readOnly: true
            - name: alloy-data-volume
              mountPath: /var/lib/alloy
      securityContext:
        runAsUser: 200
        runAsGroup: 2000
        fsGroup: 2000
      volumes:
        - name: alloy-config-volume
          secret:
            secretName: alloy
            items:
              - key: config.alloy
                path: config.alloy
  volumeClaimTemplates:
    - metadata:
        name: alloy-data-volume
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: monitoring-alloy-volume
        storageClassName: native-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
