apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      path: /alloy/metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy-service
