apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: sso
  labels:
    app.kubernetes.io/name: keycloak
spec:
  serviceName: keycloak-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.4.2
          args: ["start"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KC_HOSTNAME
              value: "https://sso.sogeor.com"
            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_CACHE
              value: "ispn"
            - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
              value: '$(POD_IP)'
            - name: KC_CACHE_EMBEDDED_MTLS_ENABLED
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "postgres-cluster-rw"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-cluster-role
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-cluster-role
                  key: password
            - name: KC_DB_POOL_INITIAL_SIZE
              value: "10"
            - name: KC_DB_POOL_MAX_SIZE
              value: "10"
            - name: KC_DB_POOL_MIN_SIZE
              value: "10"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-bootstrap-secret
                  key: username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-bootstrap-secret
                  key: password
            - name: KC_FEATURES
              value: "account-api:v1,account:v3,admin-api:v1,admin-fine-grained-authz:v2,admin:v2,authorization:v1,ciba:v1,client-policies:v1,device-flow:v1,docker:v1,dpop:v1,hostname:v2,impersonation:v1,login:v2,oid4vc-vci:v1,opentelemetry:v1,organization:v1,par:v1,passkeys:v1,persistent-user-sessions:v1,quick-theme:v1,recovery-codes:v1,rolling-updates:v2,step-up-authentication:v1,token-exchange-standard:v2,update-email:v1,user-event-metrics:v1,web-authn:v1"
          ports:
            - name: http
              containerPort: 8080
            - name: http-management
              containerPort: 9000
            - name: jgroups
              containerPort: 7800
            - name: jgroups-fd
              containerPort: 57800
          startupProbe:
            httpGet:
              path: /health/started
              port: http-management
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http-management
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            httpGet:
              path: /health/live
              port: http-management
            periodSeconds: 10
            failureThreshold: 12
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1700Mi
