apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  namespace: sso
spec:
  endpoints:
    - interval: 15s
      scrapeTimeout: 10s
      port: http-management
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-service
