apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 16Gi
        kraftMetadata: shared
        deleteClaim: false
        class: native-storage
        selector:
          app.kubernetes.io/name: kafka-broker-volume
