apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-cluster-exporter
  namespace: api
spec:
  endpoints:
    - interval: 30s
      scrapeTimeout: 10s
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb-cluster-exporter-service
