apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notifications-v1
  namespace: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notifications
      app.kubernetes.io/version: v1
