apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-cluster
  namespace: api
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-cluster
      cnpg.io/podRole: instance
  podMetricsEndpoints:
    - port: metrics
      scheme: https
      tlsConfig:
        ca:
          secret:
            name: postgres-cluster-ca
            key: ca.crt
        serverName: postgres-cluster-rw
