apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-cluster-pooler-rw
  namespace: api
spec:
  cluster:
    name: postgres-cluster
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
