apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-postgres-cluster-volume-1
  labels:
    app.kubernetes.io/name: api-postgres-cluster-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 16Gi
  local:
    path: /root/data/api/postgres-cluster/volume-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "maxwell"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: native-storage
