apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payments-v1
  namespace: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payments
      app.kubernetes.io/version: v1
