apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oauth2-proxy
  namespace: api
spec:
  endpoints:
    - interval: 15s
      scrapeTimeout: 10s
      path: /metrics
      port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy-service
