apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: api
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
              - "https://sso.sogeor.com/realms/system/*"
      to:
        - operation:
            hosts:
              - "api.sogeor.com"
              - "api.sogeor.com:*"
            notPaths:
              - "/oauth2/{**}"
              - "/{*}/{*}/actuator"
              - "/{*}/{*}/actuator/{**}"
    - to:
        - operation:
            hosts:
              - "api.sogeor.com"
              - "api.sogeor.com:*"
            paths:
              - "/robots.txt"
              - "/oauth2/{**}"
              - "/{*}/{*}/actuator"
              - "/{*}/{*}/actuator/{**}"
