apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: sso
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
              - "sso.sogeor.com"
              - "sso.sogeor.com:*"
