apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: payments-postgres-cluster
  namespace: api
spec:
  cluster:
    name: postgres-cluster
  name: payments
  owner: payments
  template: "template0"
  encoding: "UTF8"
  localeCollate: "C"
  localeCType: "C"
